name: image-service-build-test-deploy
run-name: ${{ github.actor }} - image-service-build-test-deploy
on: [ push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          cd ./node-mircoservice
          npm build

      - name: Testing
        run: |    
          cd ./node-mircoservice
          npm test

  deploy:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./ImageService/
          push: true
          tags: docker.io/devve00/patient_journal_test:image_service